### ISSUE TITLE
Not building, missing jansson.h

### ISSUE THREAD

**Issue by sigurdga** [maplechori/jstata#1]
Hi. I just jstata and tried to install it.

> CC(target) Release/obj.target/stata/stata/stata.o
> In file included from ../stata/stata.c:20:0:
> ../stata/stataread.h:35:21: fatal error: jansson.h: No such file or directory
> compilation terminated.

No jansson.h in this repository.

**Comment by sigurdga** [comment]
I needed libjansson-dev. Maybe something to put into the README?

**Comment by maplechori** [comment]
You are right. I have added a static copy of the library in the repository.
