### ISSUE TITLE
Error: The platform "darwin" is incompatible with this module.

### ISSUE THREAD

**Issue by farshed** [maplechori/jstata#2]
I'm trying to install this package in my node.js project and I get this error.

```
error jstata@0.1.3: The platform "darwin" is incompatible with this module.
error Found incompatible module.
```

I'm on macOS Catalina with Node v13.7.0.

**Comment by maplechori** [comment]
I'll review and fix

**Comment by maplechori** [comment]
You will need to download the updated version. I removed the requirement of malloc.h and added the darwin target.

- brew install jansson
- Install Python 2.7.x
- npm install ffi
- npm install ref
